# Generated by Django 4.2.24 on 2025-10-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profilePpics/')),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('disc', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Business & Finance', 'Business & Finance'), ('Education & Learning', 'Education & Learning'), ('Health & Wellness', 'Health & Wellness'), ('Lifestyle', 'Lifestyle'), ('Food & Recipes', 'Food & Recipes'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Creative Arts', 'Creative Arts'), ('Science & Knowledge', 'Science & Knowledge'), ('Sports & Fitness', 'Sports & Fitness'), ('Environment & Social', 'Environment & Social')], max_length=50)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogApp.users', to_field='username')),
            ],
        ),
    ]
