# Generated by Django 6.0.2 on 2026-04-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='role',
            field=models.CharField(default='normal_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogApp.users'),
        ),
    ]
