# Generated by Django 6.0.2 on 2026-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_profiles_role_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
