# Generated by Django 6.0.2 on 2026-05-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_profiles_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='blogApp.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
