# Generated by Django 6.0.2 (repaired placeholder)
from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('blogApp', '0007_rename_author_posts_username_users_followers_and_more'),
    ]

    operations = [
        # This migration was previously corrupted (missing Migration class).
        # Kept as a no-op to unblock Django commands.
    ]
