# Generated by Django 6.0.2 on 2026-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
