# Generated by Django 6.0.2 on 2026-05-19
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_posts_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='blogApp.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='blogApp.users')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]

