# Generated by Django 6.0.2 on 2026-05-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_post_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletionaudits',
            name='model_name',
        ),
        migrations.AlterField(
            model_name='postuserlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
