# Generated by Django 6.0.2 on 2026-05-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_posts_category_notification_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
